### ISSUE TITLE
Did you release 1.0.6 version of this package? Was it mistake that the newest is 1.0.5

### ISSUE THREAD

**Issue by karolwydmuch** [Dmc0125/html-prettify#12]
Like in the title above I would ask you why and when you release the newest version of this package. I really like how it handle HTML but I need to pass options to prettify function but I can't. 

Do you plan to add functionality to convert whole HTML file to one line (smth like optimization or version harder to read when you look at source of html page)?

**Comment by Dmc0125** [comment]
The versions on npm are corresponding to the versions on github. I just forgot to publish it to npm, but differences were just some documentation changes and dev dependecies updates.

The options in README are there by mistake, but i plan to implement the functionality in the future.

I do not plan to add functionality to convert the whole HTML file to one line for now, maybe at some time in the future.
